### PR TITLE
added Deafult widget for Bengali language

### PR DESCRIPTION
**Pull request by sagorbrur**
Hi,
I added Deafult Widget for Bengali language(bn). 
Please check, if possible please merge.

thanks and regards
Sagor

### CODE REVIEW

**Comment by julien-c** [comment]
Great, thank you

**Comment by sagorbrur** [comment]
Thank you so much.

**Comment by julien-c** [comment]
Deployed to huggingface.co: https://huggingface.co/sagorsarker/bangla-bert-base

**Comment by julien-c** [comment]
(also cc @mapmeld who pushed a Bengali model before)

**Pull request merged**
